all:
	gcc -Iinclude/ src/app.c src/camera.c src/main.c src/scene.c src/utils.c src/texture.c src/ostrich.c src/labyrinth.c src/you_won.c -lobj -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32 -lm -w -o origamiOstrich.exe -Wall -Wextra -Wpedantic 

linux:
	gcc -Iinclude/ src/app.c src/camera.c src/main.c src/scene.c src/utils.c src/texture.c src/ostrich.c src/labyrinth.c src/you_won.c -lobj -lSDL2 -lSDL2_image -lGL -lm -o origin -Wall -Wextra -Wpedantic
